### PR TITLE
Database extraction portion of the Bridge

### PR DESCRIPTION
**Pull request by mmulich**
### Intention of this changeset

This provides the database extraction to filesystem portion of the Bridge application. It's setup as a standalone application with Concourse integration. Though, at this time the division isn't exactly apparent.

This doesn't touch into existing part of this project. The intention there is to get this bulky part in and then do minor adjustments from there.

### What it does...

This is a Python package but setup as a Utility Container (isolated command environment). The container provides the Concourse Resource interface (i.e. `check`, `in` & `out`). Though, only a small portion of the `in` is implemented as part of these changes.

### Testing

The provided `show-extracted-content.yml` pipeline proves that the job extracts the specific content to the filesystem and another job prints it for viewing the Concourse UI.

```
fly ... set-pipeline -p extracted -c concourse/show-extracted-content.yml
fly ... unpause-pipeline -p extracted
fly ... trigger-job -j extracted/extract-content
fly ... watch -j extracted/extract-content
```

### CODE REVIEW

**Comment by mmulich** [comment]
Screen Shot 2019-08-12 at 17 56 15

**Comment by mmulich** [comment]
The container probably needs rebuilt and released with @karenc's addition of a commit. Just FYI...

**Comment by mmulich** [comment]
I've rebuilt and pushed the resource container image.

**Comment by c0ldcalamari** [comment]
I ran into this error, when trying to watch job - 

```
brenda-openstax:rap-spike-concourse brenda$ git pull
Already up to date.
brenda-openstax:rap-spike-concourse brenda$ fly -t dev trigger-job -j extracted/extract-content
started extracted/extract-content #2
brenda-openstax:rap-spike-concourse brenda$ fly -t dev watch -j extracted/extract-content
Content not found: 4b5aaf32-1de1-419b-bdc0-4e0a7f6daf0f@27
Traceback (most recent call last):
  File "/opt/resource/in", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bridge/concourse.py", line 44, in wrapper
    print(json.dumps(func(input_, env, args)))
  File "/usr/local/lib/python3.7/site-packages/bridge/scripts/ci_resource_in.py", line 54, in main
    f.write(json.dumps(content, sort_keys=True, indent=2))
UnboundLocalError: local variable 'content' referenced before assignment
failed
```

**Comment by c0ldcalamari** [comment]
Confirmed - Successfully Extracted Content

Screen Shot 2019-08-13 at 4 42 33 PM

**Review by c0ldcalamari — APPROVED** [review]

**Comment by karenc** [comment]
I just tried out the pipeline for the first time as well :joy: Works for me :+1:

**Review by m1yag1 — APPROVED** [review]

**Pull request merged**
